spring:
  application:
    name: spring-ai
  ai:
    ollama:
      chat:
        model: deepseek-r1:1.5b
      base-url: http://localhost:11434
    openai:
      api-key: sk-916a0d3a9c66449db8685ff45a527345
      chat:
        base-url: https://dashscope.aliyuncs.com/compatible-mode
        options:
          model: qwen-plus
          temperature: 0.8

server:
  port: 8088

logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
    com.haohaoxuexi.springai: debug