spring:
  application:
    name: spring-ai
  ai:
    ollama:
      chat:
        model: deepseek-r1:1.5b
      base-url: http://localhost:11434
    openai:
      api-key: ${Qwen-API}
      chat:
        base-url: https://dashscope.aliyuncs.com/compatible-mode
        options:
          model: qwen-plus

server:
  port: 8088

logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
    com.haohaoxuexi.springai: debug